/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * Fake server API
 * API для тестирования кодогенерации
 * OpenAPI spec version: 1.0.0
 */
import * as axios from 'axios';
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios'
import type {
  DeleteUser200,
  GetUser200,
  UpdateUser200,
  UpdateUserBody
} from '../fakeServerAPI.schemas'



  /**
 * Возвращает информацию о пользователе по ID.
 * @summary Получение пользователя по ID
 */
export const getUser = <TData = AxiosResponse<GetUser200>>(
    id: number, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/users/${id}`,options
    );
  }
/**
 * Обновляет данные пользователя по ID.
 * @summary Обновление данных пользователя по ID
 */
export const updateUser = <TData = AxiosResponse<UpdateUser200>>(
    id: number,
    updateUserBody: UpdateUserBody, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.put(
      `/users/${id}`,
      updateUserBody,options
    );
  }
/**
 * Удаляет пользователя по ID.
 * @summary Удаление пользователя по ID
 */
export const deleteUser = <TData = AxiosResponse<DeleteUser200>>(
    id: number, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.delete(
      `/users/${id}`,options
    );
  }
export type GetUserResult = AxiosResponse<GetUser200>
export type UpdateUserResult = AxiosResponse<UpdateUser200>
export type DeleteUserResult = AxiosResponse<DeleteUser200>
