/* tslint:disable */
/* eslint-disable */
/**
 * Fake server API
 * API для тестирования кодогенерации
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface GetUser200ResponseUser
 */
export interface GetUser200ResponseUser {
    /**
     * 
     * @type {number}
     * @memberof GetUser200ResponseUser
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof GetUser200ResponseUser
     */
    'email'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetUser200ResponseUser
     */
    'phone'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetUser200ResponseUser
     */
    'password'?: string;
}

