/* tslint:disable */
/* eslint-disable */
/**
 * Fake server API
 * API для тестирования кодогенерации
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface GetUser400ResponseErrorsInner
 */
export interface GetUser400ResponseErrorsInner {
    /**
     * 
     * @type {string}
     * @memberof GetUser400ResponseErrorsInner
     */
    'msg'?: GetUser400ResponseErrorsInnerMsgEnum;
}

export const GetUser400ResponseErrorsInnerMsgEnum = {
    UserIdMustBeAnInteger: 'User ID must be an integer'
} as const;

export type GetUser400ResponseErrorsInnerMsgEnum = typeof GetUser400ResponseErrorsInnerMsgEnum[keyof typeof GetUser400ResponseErrorsInnerMsgEnum];


