/* tslint:disable */
/* eslint-disable */
/**
 * Fake server API
 * API для тестирования кодогенерации
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface LoginUserRequest
 */
export interface LoginUserRequest {
    /**
     * Email пользователя. Либо это поле, либо телефон должно быть заполнено.
     * @type {string}
     * @memberof LoginUserRequest
     */
    'email'?: string;
    /**
     * Телефон пользователя. Либо это поле, либо email должно быть заполнено.
     * @type {string}
     * @memberof LoginUserRequest
     */
    'phone'?: string;
    /**
     * Пароль пользователя. Обязательное поле.
     * @type {string}
     * @memberof LoginUserRequest
     */
    'password': string;
}

