/* tslint:disable */
/* eslint-disable */
/**
 * Fake server API
 * API для тестирования кодогенерации
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface LoginUser401Response
 */
export interface LoginUser401Response {
    /**
     * 
     * @type {string}
     * @memberof LoginUser401Response
     */
    'message'?: LoginUser401ResponseMessageEnum;
}

export const LoginUser401ResponseMessageEnum = {
    EmailNotFound: 'Email not found',
    IncorrectPassword: 'Incorrect password'
} as const;

export type LoginUser401ResponseMessageEnum = typeof LoginUser401ResponseMessageEnum[keyof typeof LoginUser401ResponseMessageEnum];


