/* tslint:disable */
/* eslint-disable */
/**
 * Fake server API
 * API для тестирования кодогенерации
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface RegistrationPost400ResponseErrorsInner
 */
export interface RegistrationPost400ResponseErrorsInner {
    /**
     * 
     * @type {string}
     * @memberof RegistrationPost400ResponseErrorsInner
     */
    'msg'?: string;
    /**
     * 
     * @type {string}
     * @memberof RegistrationPost400ResponseErrorsInner
     */
    'param'?: string;
    /**
     * 
     * @type {string}
     * @memberof RegistrationPost400ResponseErrorsInner
     */
    'location'?: string;
}

