/* tslint:disable */
/* eslint-disable */
/**
 * Fake server API
 * API для тестирования кодогенерации
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface RegistrationPost200ResponseData
 */
export interface RegistrationPost200ResponseData {
    /**
     * 
     * @type {string}
     * @memberof RegistrationPost200ResponseData
     */
    'email'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof RegistrationPost200ResponseData
     */
    'phone'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof RegistrationPost200ResponseData
     */
    'clientId'?: number;
}

