/* tslint:disable */
/* eslint-disable */
/**
 * Fake server API
 * API для тестирования кодогенерации
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { RegistrationPost400ResponseErrorsInner } from './registration-post400-response-errors-inner';

/**
 * 
 * @export
 * @interface RegistrationPost400Response
 */
export interface RegistrationPost400Response {
    /**
     * 
     * @type {Array<RegistrationPost400ResponseErrorsInner>}
     * @memberof RegistrationPost400Response
     */
    'errors'?: Array<RegistrationPost400ResponseErrorsInner>;
}

