/* tslint:disable */
/* eslint-disable */
/**
 * Fake server API
 * API для тестирования кодогенерации
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { RegistrationPost200ResponseData } from './registration-post200-response-data';

/**
 * 
 * @export
 * @interface RegistrationPost200Response
 */
export interface RegistrationPost200Response {
    /**
     * 
     * @type {string}
     * @memberof RegistrationPost200Response
     */
    'message'?: string;
    /**
     * 
     * @type {RegistrationPost200ResponseData}
     * @memberof RegistrationPost200Response
     */
    'data'?: RegistrationPost200ResponseData;
}

