/* tslint:disable */
/* eslint-disable */
/**
 * Fake server API
 * API для тестирования кодогенерации
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { UpdateUser400ResponseErrorsInner } from './update-user400-response-errors-inner';

/**
 * 
 * @export
 * @interface UpdateUser400Response
 */
export interface UpdateUser400Response {
    /**
     * 
     * @type {Array<UpdateUser400ResponseErrorsInner>}
     * @memberof UpdateUser400Response
     */
    'errors'?: Array<UpdateUser400ResponseErrorsInner>;
}

