/* tslint:disable */
/* eslint-disable */
/**
 * Fake server API
 * API для тестирования кодогенерации
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { GetUser200ResponseUser } from './get-user200-response-user';

/**
 * 
 * @export
 * @interface UpdateUser200Response
 */
export interface UpdateUser200Response {
    /**
     * 
     * @type {string}
     * @memberof UpdateUser200Response
     */
    'message'?: string;
    /**
     * 
     * @type {GetUser200ResponseUser}
     * @memberof UpdateUser200Response
     */
    'user'?: GetUser200ResponseUser;
}

