/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * Fake server API
 * API для тестирования кодогенерации
 * OpenAPI spec version: 1.0.0
 */
import * as axios from 'axios';
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios'
import type {
  LoginUser200,
  LoginUserBody,
  RegistrationPost200,
  RegistrationPostBody
} from '../fakeServerAPI.schemas'



  /**
 * Эндпоинт для регистрации нового пользователя с валидацией полей.
 * @summary Регистрация пользователя
 */
export const registrationPost = <TData = AxiosResponse<RegistrationPost200>>(
    registrationPostBody: RegistrationPostBody, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.post(
      `/register`,
      registrationPostBody,options
    );
  }
/**
 * Эндпоинт для авторизации пользователя с проверкой email/телефона и пароля.
 * @summary Авторизация пользователя
 */
export const loginUser = <TData = AxiosResponse<LoginUser200>>(
    loginUserBody: LoginUserBody, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.post(
      `/login`,
      loginUserBody,options
    );
  }
export type RegistrationPostResult = AxiosResponse<RegistrationPost200>
export type LoginUserResult = AxiosResponse<LoginUser200>
